### PR TITLE
Fix deploy to use valid docker image names including tags

### LINKED ISSUE #19: Unable to deploy private function with a tag on the image
Unable to deploy a function with an image that is in a private repository (either Docker Hub, or private) when using a tag on the image. `private-registry.com/burtonr/test-fn:0.1`

## Expected Behaviour

Deploy function successful

## Current Behaviour

The CLI returns
```
Unexpected status: 400, message: Invalid registry auth
```

The log message in `faas-swarm`:
```
Error building registry auth configuration: invalid reference format
```

This is the line that throws the error: https://github.com/openfaas/faas-swarm/blob/master/handlers/deploy.go#L194

## Possible Solution

We'd need to parse the `dockerImage` input to see if there is a tag being used. If so, call the `WithTag()`, otherwise call the current `WithName()`

Or, possibly update it to _always_ call the `WithTag()` function, by setting the tag to `latest` if it's not supplied. That way there wouldn't be 2 different code paths to follow...

## Steps to Reproduce (for bugs)

1. Create a function and update the `function.yml` `image` to use a tag: `burtonr/test-fn:0.1`
2. Push the image to a private registry, Docker Hub or private instance
3. Deploy the function to a Swarm OpenFaaS cluster
4. Observe the CLI response and `faas-swarm` logs

## Context

Unable to use versions of functions from my private registry

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker 18.03.0-ce
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm 
* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 17.10 (also tested on Play-With-Docker)
* Link to your project or a code example to reproduce issue:
_it's private_ :stuck_out_tongue_winking_eye:

### PR DESCRIPTION
**Pull request by BurtonR**
## Description
This resolves the issue #19 that throws an error when using
a tag on the image name.

There are several variations to a valid docker image name.
Repository may, or may not, be included. Default is docker.io.
Username may, or may not, be included.
Repository name is always included.
An image tag may, or may not, be included. Default is 'latest'.

This update takes all those scenarios into account when getting
the authentication credentials to allow private functions
to be deployed from docker hub, or another repository

## Motivation and Context

- [X] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
Resolves #19 

## How Has This Been Tested?

Updated unit tests in the `registryauth_test.go` file to include test cases without a repository and test cases with an image tag.

Also, verified by: 
* Create a private function (on hub.docker.com)
* `faas deploy -a`  with image as: `burtonr/pvt-tester`
* `faas deploy -a` with image as: `burtonr/pvt-tester:latest`
* `faas deploy -a` with image as: `burtonr/pvt-tester:0.1`
* `faas deploy` with a new template. Image as `tester`
* `faas deploy -a` with image as `burtonr.azurecr.io/burtonr/pvt-tester`
* `faas deploy -a` with image as `burtonr.azurecr.io/burtonr/pvt-tester:latest`

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

File: handlers/deploy.go [hunk 1]
```diff
@@ -190,8 +190,11 @@ func buildEnv(envProcess string, envVars map[string]string) []string {
 // BuildEncodedAuthConfig for private registry
 func BuildEncodedAuthConfig(basicAuthB64 string, dockerImage string) (string, error) {
 	// extract registry server address
+	if len(strings.Split(dockerImage, "/")) < 3 {
```
Comment (alexellis) [inline handlers/deploy.go]: I think we can document this better.. when we read it again in 6 months it will look like magic

File: test/registryauth_test.go [hunk 2]
```diff
@@ -47,7 +54,7 @@ func testValidEncodedAuthConfig(t *testing.T, user, password, imageName, expecte
 	}
 
 	if user != authConfig.Username {
-		t.Log("Auth config username mismatch", user, authConfig.Username)
+		t.Logf("Auth config username mismatch want %s, got: %s", user, authConfig.Username)
```
Comment (alexellis) [inline test/registryauth_test.go]: Great way to improve the readability of this test. Do tests fail if you keep the test code but revert the code fix?

Comment (BurtonR) [reply test/registryauth_test.go]: The tests were passing with this line in it's original state, but I was having trouble knowing what the problem was, so I fixed it :smile:

File: handlers/deploy.go (hunk 1 above)
Comment (BurtonR) [reply handlers/deploy.go]: Good point!

**Comment by BurtonR** [comment]
I updated the description for the `BuildEncodedAuthConfig` function to _hopefully_ explain what was going on with the `strings.Split` to avoid any confusion later.

File: test/registryauth_test.go (hunk 2 above)
Comment (BurtonR) [reply test/registryauth_test.go]: I just re-read your comment. I misunderstood you the first time around...
Yes, by only adding in the additional test cases, the tests would fail. In the original state of the code, the repository _must_ be included, and no tag could be used. This is due to the assumptions that the `WithName` function parsed the input (from the docker library)

Comment (alexellis) [reply test/registryauth_test.go]: I was referring to the Logs usage / want/got values are really important in a test failure 👍

**Comment by alexellis** [comment]
@BurtonR  / @rgee0 are we good to merge this?

**Comment by BurtonR** [comment]
I'm confident this is ready to get merged

File: handlers/deploy.go [hunk 3]
```diff
@@ -187,11 +187,15 @@ func buildEnv(envProcess string, envVars map[string]string) []string {
 	return env
 }
 
-// BuildEncodedAuthConfig for private registry
+// BuildEncodedAuthConfig parses the image name for a repository, user name, and image name
+// If a repository is not included (ie: username/function-name), 'docker.io/' will be appended
```
Comment (rgee0) [inline handlers/deploy.go]: Sorry to be pedantic but given comments are meant to help someone else understand then `appended` should be `prepended`

Comment (BurtonR) [reply handlers/deploy.go]: That's a good point! I couldn't think of that word at the time! Good catch :smile:

**Comment by BurtonR** [comment]
Updated the comment to use the appropriate terminology to avoid confusion. Thanks @rgee0!

**Comment by alexellis** [comment]
OK I'll merge and cut a release. Please can you re-run your scenarios with the official image and then raise a PR to update faas-swarm in the faas repo? That way we can start benefiting from your hard work 💯 😄

**Comment by alexellis** [comment]
@rgee0 thanks for the review 👍

File: handlers/deploy.go [hunk 4]
```diff
@@ -187,11 +187,15 @@ func buildEnv(envProcess string, envVars map[string]string) []string {
 	return env
 }
 
-// BuildEncodedAuthConfig for private registry
+// BuildEncodedAuthConfig parses the image name for a repository, user name, and image name
+// If a repository is not included (ie: username/function-name), 'docker.io/' will be prepended
 func BuildEncodedAuthConfig(basicAuthB64 string, dockerImage string) (string, error) {
-	// extract registry server address
+	// use docker.io if no repository was included
+	if len(strings.Split(dockerImage, "/")) < 3 {
```
Comment (alexellis) [inline handlers/deploy.go]: I previously gave the feedback that we shouldn't use a magic number `3` - it may have been on the CLI repo.

What does 3 mean and how can we make sure it's clear going forward?

Comment (BurtonR) [reply handlers/deploy.go]: My next PR in this repo will update that to be more clear.

|1|2|3|
|---|---|---|
|repository|username|image|

So, if there are less than 3, there's no repository included. During testing of this PR, I did also verify that this will still work as expected with _only_ an image name `function-1` for example

Comment (rgee0) [reply handlers/deploy.go]: Lets not over-think this.  Magic numbers should, as a minimum, be extracted into constants and given a meaningful name to assist readability.  `const fullImagePathLength int = 3` turns the existing code into `if len(strings.Split(dockerImage, "/")) < fullImagePathLength {` which even at a minimal level is more readable.

Taking it further we could wrap the left hand side into a fn called imagePathLength() we get:
```
if imagePathLength(dockerImage) < fullImagePathLength {
```

I lack imagination when naming things but I hope this helps demonstrate the point.

Comment (alexellis) [reply handlers/deploy.go]: `fullImagePath` means nothing to a reader - the suggestion was to express this differently - via two named variables for 1 and 2 showing that 1 was username (namespace) and 2 was including a domain name.

Comment (rgee0) [reply handlers/deploy.go]: Apologies, didn't see the suggestion only the question.
